language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    allow_failures:
        - php: 7
        - php: hhvm

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script: phpunit
