language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

services:
    - mysql

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script: echo "SHOW DATABASES;" | mysql -u travis -h 127.0.0.1
